# Generated by Django 6.0.6 on 2026-06-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Yilning nechanchi kuni (1-365)', unique=True)),
                ('text', models.TextField(verbose_name='Kun iborasi')),
            ],
        ),
    ]
